# Generated by Django 5.0.3 on 2024-03-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='userincome',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userincome.source'),
        ),
    ]
